In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
lst_file = "omni2_f8X1myCa23.lst"
fmt_file = "omni2_f8X1myCa23.fmt"

In [3]:
with open(fmt_file, "r") as f:
    print(f.read())

  FORMAT OF THE SUBSETTED FILE

    ITEMS                      FORMAT

 1 YEAR                          I4
 2 DOY                           I4
 3 Hour                          I3
 4 Scalar B, nT                  F6.1
 5 BX, nT (GSE, GSM)             F6.1
 6 BY, nT (GSM)                  F6.1
 7 BZ, nT (GSM)                  F6.1
 8 SW Plasma Temperature, K      F9.0
 9 SW Proton Density, N/cm^3     F6.1
10 SW Plasma Speed, km/s         F6.0
11 E elecrtric field             F7.2
12 Kp index                      I3
13 Dst-index, nT                 I6
14 f10.7_index                   F6.1
15 AE-index, nT                  I5

In [4]:
column_names = [
    "year",
    "doy",
    "hour",
    "bt",
    "bx_gsm",
    "by_gsm",
    "bz_gsm",
    "temperature",
    "density",
    "speed",
    "ey",
    "kp",
    "dst",
    "f107",
    "ae",
]

In [8]:
df = pd.read_csv(
    lst_file,
    sep=r"\s+",
    header=None,
    names=column_names,
    engine="python"
)

In [7]:
import pandas as pd

print(pd.__version__)

3.0.3

In [9]:
df.head()

,year,doy,hour,bt,bx_gsm,by_gsm,bz_gsm,temperature,density,speed,ey,kp,dst,f107,ae
0,2023,1,0,5.6,-1.9,4.6,0.4,111138.0,2.4,603.0,-0.24,23,-23,147.5,132
1,2023,1,1,5.0,-3.9,-0.7,0.5,157287.0,2.6,582.0,-0.29,23,-21,147.5,97
2,2023,1,2,5.2,-3.9,-1.5,1.2,143309.0,2.6,581.0,-0.70,23,-23,147.5,133
3,2023,1,3,5.0,-3.4,1.4,0.6,138155.0,2.4,576.0,-0.35,30,-26,147.5,180
4,2023,1,4,4.9,-2.4,2.6,1.0,130313.0,2.5,585.0,-0.58,30,-26,147.5,139

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26304 entries, 0 to 26303
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         26304 non-null  int64
 1   doy          26304 non-null  int64
 2   hour         26304 non-null  int64
 3   bt           26304 non-null  float64
 4   bx_gsm       26304 non-null  float64
 5   by_gsm       26304 non-null  float64
 6   bz_gsm       26304 non-null  float64
 7   temperature  26304 non-null  float64
 8   density      26304 non-null  float64
 9   speed        26304 non-null  float64
 10  ey           26304 non-null  float64
 11  kp           26304 non-null  int64
 12  dst          26304 non-null  int64
 13  f107         26304 non-null  float64
 14  ae           26304 non-null  int64
dtypes: float64(9), int64(6)
memory usage: 3.0 MB

In [12]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
year,26304.0,2024.000000,8.161395e-01,2023.00,2023.00,2024.00,2025.00,2025.00
doy,26304.0,183.166971,1.054648e+02,1.00,92.00,183.00,274.25,366.00
hour,26304.0,11.500000,6.922318e+00,0.00,5.75,11.50,17.25,23.00
bt,26304.0,11.863374,6.918281e+01,0.80,4.90,6.30,8.10,999.90
bx_gsm,26304.0,4.807736,6.970435e+01,-40.00,-3.10,0.10,3.10,999.90
by_gsm,26304.0,4.760858,6.973947e+01,-34.10,-3.10,-0.10,3.10,999.90
bz_gsm,26304.0,4.767571,6.968686e+01,-42.20,-2.00,-0.10,1.90,999.90
temperature,26304.0,288629.546039,1.325702e+06,3802.00,46359.75,80794.00,142591.50,9999999.00
density,26304.0,23.531330,1.296478e+02,0.10,3.20,4.90,7.90,999.90
speed,26304.0,605.168948,1.250303e+03,256.00,369.00,419.00,495.00,9999.00
ey,26304.0,18.823820,1.357552e+02,-18.23,-0.77,0.06,0.91,999.99
kp,26304.0,21.394503,1.362433e+01,0.00,10.00,20.00,30.00,90.00
dst,26304.0,-13.121655,2.511723e+01,-406.00,-21.00,-9.00,1.00,71.00
f107,26304.0,168.709672,3.627439e+01,111.70,144.30,163.10,182.40,412.90
ae,26304.0,216.652334,2.130913e+02,6.00,64.00,136.00,304.00,2338.00

In [13]:
missing_values = {
    "bt": 999.9,
    "bx_gsm": 999.9,
    "by_gsm": 999.9,
    "bz_gsm": 999.9,
    "temperature": 9999999,
    "density": 999.9,
    "speed": 9999,
    "ey": 999.99,
}

df = df.replace(missing_values, np.nan)

In [16]:
df.isna().sum()

year             0
doy              0
hour             0
bt             128
bx_gsm         128
by_gsm         128
bz_gsm         128
temperature    478
density        455
speed          455
ey             494
kp               0
dst              0
f107             0
ae               0
dtype: int64

In [17]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
year,26304.0,2024.000000,0.816140,2023.00,2023.00,2024.00,2025.00,2025.00
doy,26304.0,183.166971,105.464786,1.00,92.00,183.00,274.25,366.00
hour,26304.0,11.500000,6.922318,0.00,5.75,11.50,17.25,23.00
bt,26176.0,7.031899,3.530801,0.80,4.90,6.20,8.10,68.90
bx_gsm,26176.0,-0.058240,4.061560,-40.00,-3.10,0.10,3.00,33.50
by_gsm,26176.0,-0.105348,4.578197,-34.10,-3.10,-0.20,3.00,67.60
bz_gsm,26176.0,-0.098602,3.695054,-42.20,-2.00,-0.10,1.80,31.30
temperature,25826.0,108886.860412,109956.345292,3802.00,45802.25,79330.00,137528.00,3335564.00
density,25849.0,6.345066,5.317200,0.10,3.20,4.80,7.70,87.40
speed,25849.0,439.816589,100.398780,256.00,369.00,417.00,490.00,1092.00
ey,25810.0,0.044429,1.771574,-18.23,-0.79,0.04,0.86,28.95
kp,26304.0,21.394503,13.624327,0.00,10.00,20.00,30.00,90.00
dst,26304.0,-13.121655,25.117226,-406.00,-21.00,-9.00,1.00,71.00
f107,26304.0,168.709672,36.274388,111.70,144.30,163.10,182.40,412.90
ae,26304.0,216.652334,213.091273,6.00,64.00,136.00,304.00,2338.00

In [18]:
df["datetime"] = (
    pd.to_datetime(df["year"], format="%Y")
    + pd.to_timedelta(df["doy"] - 1, unit="D")
    + pd.to_timedelta(df["hour"], unit="h")
)

In [19]:
df[["year", "doy", "hour", "datetime"]].head()

   year  doy  hour            datetime
0  2023    1     0 2023-01-01 00:00:00
1  2023    1     1 2023-01-01 01:00:00
2  2023    1     2 2023-01-01 02:00:00
3  2023    1     3 2023-01-01 03:00:00
4  2023    1     4 2023-01-01 04:00:00

In [20]:
df.set_index("datetime", inplace=True)

In [21]:
df.head()

,year,doy,hour,bt,bx_gsm,by_gsm,bz_gsm,temperature,density,speed,ey,kp,dst,f107,ae
datetime,,,,,,,,,,,,,,,
2023-01-01 00:00:00,2023,1,0,5.6,-1.9,4.6,0.4,111138.0,2.4,603.0,-0.24,23,-23,147.5,132
2023-01-01 01:00:00,2023,1,1,5.0,-3.9,-0.7,0.5,157287.0,2.6,582.0,-0.29,23,-21,147.5,97
2023-01-01 02:00:00,2023,1,2,5.2,-3.9,-1.5,1.2,143309.0,2.6,581.0,-0.70,23,-23,147.5,133
2023-01-01 03:00:00,2023,1,3,5.0,-3.4,1.4,0.6,138155.0,2.4,576.0,-0.35,30,-26,147.5,180
2023-01-01 04:00:00,2023,1,4,4.9,-2.4,2.6,1.0,130313.0,2.5,585.0,-0.58,30,-26,147.5,139

In [22]:
df.index.is_monotonic_increasing

True

In [24]:
df.index.freq

In [26]:
df.index.min()

Timestamp('2023-01-01 00:00:00')

In [27]:


df.index.max()

Timestamp('2025-12-31 23:00:00')

In [28]:
missing_timestamps = pd.date_range(
    start=df.index.min(),
    end=df.index.max(),
    freq="h"
).difference(df.index)

len(missing_timestamps)

0

In [30]:
df.to_csv("master_omni.csv")

In [34]:
solar_wind_df = df[
    ["speed", "density", "temperature"]
].copy()

In [35]:
imf_df = df[
    ["bt", "bx_gsm", "by_gsm", "bz_gsm"]
].copy()

In [36]:
kp_dst_df = df[
    ["kp", "dst"]
].copy()

In [37]:
ae_df = df[
    ["ae"]
].copy()

In [38]:
f107_df = df[
    ["f107"]
].copy()

In [39]:
solar_wind_df.to_csv("solar_wind.csv")

imf_df.to_csv("imf.csv")

kp_dst_df.to_csv("kp_dst.csv")

ae_df.to_csv("ae.csv")

f107_df.to_csv("f107.csv")

In [40]:
solar_wind_df.head()

                     speed  density  temperature
datetime
2023-01-01 00:00:00  603.0      2.4     111138.0
2023-01-01 01:00:00  582.0      2.6     157287.0
2023-01-01 02:00:00  581.0      2.6     143309.0
2023-01-01 03:00:00  576.0      2.4     138155.0
2023-01-01 04:00:00  585.0      2.5     130313.0